"""
Category 2: Indian Product Companies (Secondary Targets)
Domestic unicorns with strong engineering cultures.
"""

CATEGORY = "indian_product"
CATEGORY_LABEL = "Category 2: Indian Product Companies"

COMPANIES = [
    # Audited 2026-06-13: no Angular openings found
    # {"name": "Flipkart",  "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.flipkartcareers.com/job-search?query=Software",    "portal_type": "generic"},
    # {"name": "Swiggy",    "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.swiggy.com/search?q=Engineer",          "portal_type": "generic"},
    # {"name": "Cred",      "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.cred.club/jobs?department=Engineering",           "portal_type": "generic"},
    # {"name": "Razorpay",  "tier": "Tier_7_Domestic_Unicorn", "url": "https://razorpay.com/jobs/?department=Engineering",           "portal_type": "generic"},
    # {"name": "Zerodha",   "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.zerodha.com/",         "portal_type": "generic"},
    # {"name": "PhonePe",   "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.phonepe.com/careers/jobs/?department=Engineering",     "portal_type": "generic"},
    # {"name": "Groww",     "tier": "Tier_7_Domestic_Unicorn", "url": "https://groww.in/careers",              "portal_type": "generic"},
    # {"name": "Zepto",     "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.zeptonow.com/careers/engineering",     "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found
    # {"name": "Paytm",     "tier": "Tier_7_Domestic_Unicorn", "url": "https://jobs.lever.co/paytm",          "portal_type": "lever"},
    # --- New Additions ---
    # {"name": "Zeta",      "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.zeta.tech/jobs/?department=Engineering",           "portal_type": "generic"},
    # {"name": "MoEngage",  "tier": "Tier_7_Domestic_Unicorn", "url": "https://moengage.hire.trakstar.com/",  "portal_type": "generic"},
    # {"name": "Darwinbox", "tier": "Tier_7_Domestic_Unicorn", "url": "https://darwinbox.com/en-us/careers", "portal_type": "generic"},
    {"name": "Keka HR", "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.keka.com/careers", "portal_type": "generic"},
    # {"name": "Acko", "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.acko.com/careers/jobs/", "portal_type": "generic"},
    # {"name": "Innovaccer", "tier": "Tier_7_Domestic_Unicorn", "url": "https://innovaccer.com/careers/jobs", "portal_type": "generic"},
    # {"name": "Practo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://practo.app.param.ai/jobs/", "portal_type": "generic"},
    # {"name": "upGrad", "tier": "Tier_7_Domestic_Unicorn", "url": "https://www.upgrad.com/careers/", "portal_type": "generic"},
    # {"name": "Testbook", "tier": "Tier_7_Domestic_Unicorn", "url": "https://testbook.com/careers", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found
    # {"name": "ixigo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.smartrecruiters.com/ixigo", "portal_type": "smartrecruiters"},
    # {"name": "HighRadius", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/highradius?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "LeadSquared", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.leadsquared.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found
    # {"name": "Zenoti", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.zenoti.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Oracle Cloud / Broken Greenhouse board)
    # {"name": "Icertis", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/icertis?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "MindTickle", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.mindtickle.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Druva", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.druva.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Eightfold AI", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.eightfold.ai/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Phenom People", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.phenom.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Edifecs", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.edifecs.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Trakstar / Broken Greenhouse board)
    # {"name": "Whatfix", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/whatfix?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "Amagi", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.amagi.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Gupshup", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.gupshup.io/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Capillary Technologies", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.capillarytech.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Freshworks", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.freshworks.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Kissflow", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.kissflow.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "RateGain", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.rategain.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Chargebee", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.chargebee.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Yellow.ai", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.yellow.ai/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "CleverTap", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.clevertap.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "WebEngage", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.webengage.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Netcore Cloud", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.netcorecloud.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Vymo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.vymo.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "ClearTax", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.cleartax.in/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "OfBusiness", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.ofbusiness.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Khatabook", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.khatabook.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Navi", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.navi.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Yubi", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.go-yubi.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Open Financial Technologies", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.open.money/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Lendingkart", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.lendingkart.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "CoinDCX", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/coindcx?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "CoinSwitch", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/coinswitch?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Mudrex", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/mudrex?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "WazirX", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.wazirx.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Pratilipi", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.pratilipi.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Pocket FM", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/pocketfm?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Kuku FM", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.kukufm.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Classplus", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/classplus?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Broken Greenhouse board)
    # {"name": "Eruditus", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/eruditus?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "Bizongo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.bizongo.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "ElasticRun", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.elasticrun.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Shiprocket", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/shiprocket?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Shadowfax", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/shadowfax?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Porter", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/porter?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Log9 Materials", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.log9materials.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Euler Motors", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.eulermotors.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "SUN Mobility", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.sunmobility.co.in/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Broken Greenhouse board)
    # {"name": "Ather Energy", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/atherenergy?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "Simple Energy", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.simpleenergy.in/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Ultraviolette Automotive", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.ultraviolette.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Broken Greenhouse board)
    # {"name": "Rapido", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/rapido?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "Chalo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.chalo.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Zoomcar", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.zoomcar.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Drivezy", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.drivezy.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "CarDekho", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.cardekho.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Spinny", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/spinny?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Cars24", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/cars24?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Droom", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.droom.in/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Square Yards", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.squareyards.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "NestAway", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.nestaway.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Magicbricks", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.magicbricks.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Housing.com", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.housing.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "PropTiger", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.proptiger.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "ZoloStay", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.zolostays.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Stanza Living", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.stanzaliving.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # Audited 2026-06-13: no Angular openings found (Broken Greenhouse board)
    # {"name": "Livspace", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/livspace?q=Angular&location=India", "portal_type": "greenhouse"},
    # {"name": "HomeLane", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/homelane?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Design Cafe", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.designcafe.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Pepperfry", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.pepperfry.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Furlenco", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.furlenco.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Rentomojo", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.rentomojo.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Wakefit", "tier": "Tier_7_Domestic_Unicorn", "url": "https://boards.greenhouse.io/wakefit?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "Sleepyhead", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.sleepyhead.com/jobs?q=Angular&location=India", "portal_type": "generic"},
    # {"name": "The Sleep Company", "tier": "Tier_7_Domestic_Unicorn", "url": "https://careers.thesleepcompany.in/jobs?q=Angular&location=India", "portal_type": "generic"},
]
